# Generated by Django 2.0.5 on 2018-05-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id_question',
        ),
        migrations.AlterField(
            model_name='question',
            name='name_asker',
            field=models.CharField(max_length=50, verbose_name='Can I have your name, genius?'),
        ),
    ]
